<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class Schools_m extends MY_Model
{


    protected $_table_name = 'tbl_yekt_schools';
    protected $_primary_key = 'id';
    protected $_primary_filter = 'intval';
    protected $_order_by = "id asc";

    function __construct()
    {
        parent::__construct();
    }

    public function getItems($site_id = 1)
    {
        $this->db->select('*')
            ->from('tbl_yekt_schools')
            ->where('site_id', $site_id);
        $query = $this->db->get();
        return $query->result();
    }

    public function getList($site_id = 2)
    {
        $this->db->select('site_id as category_number, id as school_id')
            ->from('tbl_yekt_schools')
            ->where('school_status', '1')
            ->where('site_id', $site_id)
            ->order_by('site_id', 'asc')
            ->order_by('id', 'asc');
        $query = $this->db->get();
        $list = $query->result();
        $ret = array();
        for ($i = 0; $i < 3; $i++) {
            $temp = array();
            foreach ($list as $item) {
                if ($item->school_id == ($i + 4)) {
                    array_push($temp, $item->category_number);
                }
            }
            array_push($ret,$temp);
        }
        return $ret;
    }

    public function publish($school_id, $publish_st, $site_id)//$stop_st==1 then enabled state, $stop_st == 0 then Disabled
    {
        $this->db->set('school_status', $publish_st);
        $this->db->where('id', $school_id);
        $this->db->update('tbl_yekt_schools');
        return $this->getItems($site_id);
    }

    public function edit($item_id, $item_name, $site_id)
    {
        $arr = array(
            'school_name' => $item_name
        );
        $this->db->where('id', $item_id);
        $this->db->update('tbl_yekt_schools', $arr);
        return $this->getItems($site_id);
    }

    public function getSchoolIdFromName($school_name)
    {
        $this->db->select('school_id')->from('schools')->where('school_name', $school_name);
        $query = $this->db->get();

        if (count($query->result()) === 0 || $query === null) return '-1';

        $ret = $query->row();

        return $ret->school_id;
    }

    public function get($id, $single = FALSE)
    {
        return parent::get($id, $single); // TODO: Change the autogenerated stub
    }

    public function get_where($array = NULL)
    {
        return parent::get_where($array); // TODO: Change the autogenerated stub
    }

    public function delete($school_id)
    {
        $this->db->where('school_id', $school_id);
        $this->db->delete('schools');
        return $this->get_all_schools();
    }

    public function get_all_schools()
    {
        $this->db->select('*')->from('schools');
        $query = $this->db->get();
        return $query->result();
    }

    public function add($school_name, $class_arr)
    {
        $arr = array(
            'school_name' => $school_name,
            'class_arr' => json_encode($class_arr),
            'stop' => '0'
        );
        $this->db->set($arr);
        $this->db->insert('schools');
        return $this->get_all_schools();

    }

    public function get_classLists($school_name)
    {
        $this->db->select('class_arr, school_id')->from('schools')->where('school_name', $school_name);
        $query = $this->db->get();
        return $query->result();
    }

    public function getSchoolNameIdFromId($school_id)
    {
        $this->db->select('school_name')->from('schools')->where('school_id', $school_id);
        $query = $this->db->get();
        $ret = $query->row();
        return $ret->school_name;
    }

    public function getSchoolTypeIdFromName($schoolTypeId)
    {
        $this->db->select('school_type_id')->from('school_types')->where('school_type_name', $schoolTypeId);
        $query = $this->db->get();
        $ret = $query->row();
        if ($ret != NULL)
            return $ret->school_type_id;
        else return 1;
    }

}
